### PR TITLE
Fix README.md markdown errors

### PR DESCRIPTION
**Pull request by Aholicknight**
I have fixed the readme by removing trailing spaces + other markdown errors that were detected.

Also how do you expect people to report problems or if something is not working if you have issues disabled? Since issues has been **disabled** from this repo I cant report this problem I am having in this screenshot which forces me to make a pull request. I have the latest version of YouTube and no matter what file uploading site I use, I get this error. I tried uploading the IPA as a zip, did not work. I tried uploading it un-compressed, did not work. 
msedge_3850790515

Some help with this would be great + for the sake of this repo **please enable issues**

Thank you.

### CODE REVIEW

**Comment by qnblackcat** [comment]
Why I turn off opening issue?

1. CercubePlus and uYouPlus share 95% of their features. If CercubePlus has a bug, uYouPlus will most likely have the same bug. 
2. Cercube itself is also much more stable than uYou. 
3. (Most important thing): I don’t have enough time to answer every single question on both repos. Especially when all the questions are almost the same...

**Comment by qnblackcat** [comment]
About your issue: Nothing wrong with the script, I‘ve just tested it and everything went through without an error. 

https://github.com/qnblackcat/CercubePlus/actions/runs/2917972688

I’m pretty sure either you did not provide a direct url to the ipa, or something is wrong with your host.

**Comment by qnblackcat** [comment]
I‘ve checked your URL which was used when you run the action. It’s definitely not a direct URL to the YouTube ipa

**Comment by Aholicknight** [comment]
> I‘ve checked your URL which was used when you run the action. It’s definitely not a direct URL to the YouTube ipa

@qnblackcat you used gofile and tested? I copied the direct link from the download button which ends in .ipa

**Comment by qnblackcat** [comment]
Well, you have to copy the url of the **downloading file** instead of the download button

**Comment by Aholicknight** [comment]
> Well, you have to copy the url of the **downloading file** instead of the download button

@qnblackcat Would I upload the IPA compressed or uncompressed?

**Comment by Aholicknight** [comment]
@qnblackcat As an example, I have uploaded the IPA to Gofile again. Would I use: 

- https://gofile.io/d/EjgQEe
or
- https://store7.gofile.io/download/c99fa314-5c83-4884-892e-1c377fe85644/YouTube.ipa

Thanks!

**Comment by qnblackcat** [comment]
Simply paste the link into the URL bar, if the download start immediately then it‘s a direct URL. I’m pretty sure it’s a second one

**Comment by Aholicknight** [comment]
> Simply paste the link into the URL bar, if the download start immediately then it‘s a direct URL. I’m pretty sure it’s a second one 

@qnblackcat That's what I used in the GitHub action and it didn't work

**Comment by qnblackcat** [comment]
That’s mean both of them are not direct URL 🤷‍♂️

This is a direct url

https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/EQvqiORRmiBEv30qTiBRl4cB80uMsj64FoXN0swwJDUVmQ?download=1

**Comment by KhangViet009** [comment]
I really like your mod Cercube ipa.  I always update the latest version every time you guys release it, everything is ok except for this one error: I use iphone 12 pro max, every time I record videos in HDR format and upload to youtube with your ipa mod, it  can only upload in normal format, not HDR.  Hope you can fix this.  thanks a lot !

**Comment by qnblackcat** [comment]
> @qnblackcat
> I really like your mod Cercube ipa. I always update the latest version every time you guys release it, everything is ok except for this one error: I use iphone 12 pro max, every time I record videos in HDR format and upload to youtube with your ipa mod, Cercube+ only show in normal format, not HDR. Hope you can fix this. thanks a lot !
> And, just seen the latest update, can you up Cercube to Version 5.3.11 ☺️

This is the better place for your issue

**Comment by MrL0** [comment]
Hello, wasn’t sure where to leave a comment but can Cercube be updated to latest 5.3.11?

**Comment by parthnayak7448** [comment]
@qnblackcat I don’t see cercube button to download video. 

Can you please share me steps how can get cercube download button?

**Comment by Aholicknight** [comment]
@qnblackcat Ok you were right, I can see why you don't want GitHub issues on this repo. Can you lock this closed pull request so no one else can comment on it?

**Pull request closed without merging**
