### PR TITLE
Workaround for known issue

### PR DESCRIPTION
**Pull request by dayanch96**
optional

### CODE REVIEW

**Comment by dayanch96** [comment]
Unfortunately, your method of hiding watermarks didn't work for me.
2022_05_19_04_15_IMG_4084
You can try to use this one:
`%hook YTAnnotationsViewController
- (void)loadFeaturedChannelWatermark {
}
%end`

or just make it 0x0 pixels like i did before :D

**Comment by dayanch96** [comment]
Here is result:
2022_05_19_06_41_IMG_4087

**Comment by qnblackcat** [comment]
I‘ve just re-added the switch. Lmk if it works

**Comment by dayanch96** [comment]
> I‘ve just re-added the switch. Lmk if it works

It works.

Btw oled black (except oled keyboard) doesn't works on 17.18.4 but works on 17.19.2. Looks like Google tested something on previous version

**Pull request merged**
